# Copyright 2025 TiDB Cloud
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# flake8: noqa

from typing import Any

# Exception classes - PEP 249 compliant
class Warning(Exception): ...
class Error(Exception): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...

class ServerStats:
    @property
    def total_rows(self) -> int: ...
    @property
    def total_bytes(self) -> int: ...
    @property
    def read_rows(self) -> int: ...
    @property
    def read_bytes(self) -> int: ...
    @property
    def write_rows(self) -> int: ...
    @property
    def write_bytes(self) -> int: ...
    @property
    def running_time_ms(self) -> float: ...

class ConnectionInfo:
    @property
    def handler(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def user(self) -> str: ...
    @property
    def database(self) -> str | None: ...
    @property
    def warehouse(self) -> str | None: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def data_type(self) -> str: ...

class Schema:
    def fields(self) -> list[Field]: ...

class Row:
    def values(self) -> tuple: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Row: ...
    def __next__(self) -> Any: ...
    def __dict__(self) -> dict: ...
    def __getitem__(self, key: int | str) -> Any: ...

class RowIterator:
    def schema(self) -> Schema: ...
    def close(self) -> None: ...
    def __iter__(self) -> RowIterator: ...
    def __next__(self) -> Row: ...
    def __aiter__(self) -> RowIterator: ...
    async def __anext__(self) -> Row: ...

class AsyncLakeConnection:
    async def info(self) -> ConnectionInfo: ...
    async def version(self) -> str: ...
    async def close(self) -> None: ...
    def last_query_id(self) -> str | None: ...
    async def kill_query(self, query_id: str) -> None: ...
    def format_sql(self, sql: str, params: Any = None) -> str: ...
    async def exec(self, sql: str, params: Any = None) -> int: ...
    async def query_row(self, sql: str, params: Any = None) -> Row: ...
    async def query_all(self, sql: str, params: Any = None) -> list[Row]: ...
    async def query_iter(self, sql: str, params: Any = None) -> RowIterator: ...
    async def stream_load(self, sql: str, data: list[list[str]]) -> ServerStats: ...
    async def load_file(
        self, sql: str, file: str, format_option: dict, copy_options: dict = None
    ) -> ServerStats: ...

class AsyncLakeClient:
    def __init__(self, dsn: str): ...
    async def get_conn(self) -> AsyncLakeConnection: ...

class BlockingLakeConnection:
    def info(self) -> ConnectionInfo: ...
    def version(self) -> str: ...
    def close(self) -> None: ...
    def last_query_id(self) -> str | None: ...
    def kill_query(self, query_id: str) -> None: ...
    def format_sql(self, sql: str, params: Any = None) -> str: ...
    def exec(self, sql: str, params: Any = None) -> int: ...
    def query_row(self, sql: str, params: Any = None) -> Row: ...
    def query_all(self, sql: str, params: Any = None) -> list[Row]: ...
    def query_iter(self, sql: str, params: Any = None) -> RowIterator: ...
    def stream_load(self, sql: str, data: list[list[str]]) -> ServerStats: ...
    def load_file(
        self, sql: str, file: str, format_option: dict, copy_options: dict = None
    ) -> ServerStats: ...

class BlockingLakeCursor:
    @property
    def description(
        self,
    ) -> list[
        tuple[str, str, int | None, int | None, int | None, int | None, bool | None]
    ]: ...
    @property
    def rowcount(self) -> int: ...
    def close(self) -> None: ...
    def execute(
        self, operation: str, params: list[Any] | tuple[Any] = None
    ) -> None | int: ...
    def executemany(
        self, operation: str, params: list[list[Any] | tuple[Any]]
    ) -> None | int: ...
    def fetchone(self) -> Row | None: ...
    def fetchmany(self, size: int = 1) -> list[Row]: ...
    def fetchall(self) -> list[Row]: ...

    # Optional DB API Extensions
    def next(self) -> Row: ...
    def __next__(self) -> Row: ...
    def __iter__(self) -> BlockingLakeCursor: ...

class BlockingLakeClient:
    def __init__(self, dsn: str): ...
    def get_conn(self) -> BlockingLakeConnection: ...
    def cursor(self) -> BlockingLakeCursor: ...
